name: Deploy Infrastructure

on:
  push:
    paths:
      - "infrastructure/website/**"

jobs:
  deploy:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Set current branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set environment
        run: |
          case ${{ env.BRANCH }} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Set terraform module source
        run: |
            case ${{ env.BRANCH }} in
              "production") echo "MODULE_SOURCE=git@github.com:jomicu/terraform-static-website-module.git" >> $GITHUB_ENV ;;
              "preprod") echo "MODULE_SOURCE=git@github.com:jomicu/terraform-static-website-module.git?ref=preprod" >> $GITHUB_ENV ;;
              "qa") echo "MODULE_SOURCE=git@github.com:jomicu/terraform-static-website-module.git?ref=qa" >> $GITHUB_ENV ;;
              *) echo "MODULE_SOURCE=git@github.com:jomicu/terraform-static-website-module.git?ref=development" >> $GITHUB_ENV ;;
            esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Replace placeholder's
        run: |
          sed -i "s/AWS_TERRAFORM_BUCKET_PLACEHOLDER/${{ secrets.AWS_TERRAFORM_BUCKET }}/g" main.tf
          sed -i "s/AWS_REGION_PLACEHOLDER/${{ secrets.AWS_REGION }}/g" main.tf
          sed -i "s/ENVIRONMENT_PLACEHOLDER/${{ env.ENVIRONMENT }}/g" main.tf
          sed -i "s/SERVICE_PLACEHOLDER/${{ secrets.AWS_SERVICE_NAME }}/g" main.tf
          sed -i "s/SOURCE_PLACEHOLDER/${{ env.MODULE_SOURCE }}/g" main.tf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

