name: Deploy Infrastructure

on:
  pull_request:
  push:
    paths:
      - "infrastructure/website/**"

jobs:
  deploy:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Set endpoint
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENDPOINT="www.${{ secrets.DOMAIN_NAME }}"" >> $GITHUB_ENV ;;
            "preprod") echo "ENDPOINT="preprod.${{ secrets.DOMAIN_NAME }}"" >> $GITHUB_ENV ;;
            "qa") echo "ENDPOINT="qa.${{ secrets.DOMAIN_NAME }}"" >> $GITHUB_ENV ;;
            *) echo "ENDPOINT="development.${{ secrets.DOMAIN_NAME }}"" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Replace placeholder's
        working-directory: "./infrastructure/website"
        run: |
          sed -i "s|AWS_TERRAFORM_BUCKET_PLACEHOLDER|${{ secrets.AWS_TERRAFORM_BUCKET }}|g" main.tf
          sed -i "s|AWS_REGION_PLACEHOLDER|${{ secrets.AWS_REGION }}|g" main.tf
          sed -i "s|ENVIRONMENT_PLACEHOLDER|${{ env.ENVIRONMENT }}|g" main.tf
          sed -i "s|SERVICE_PLACEHOLDER|${{ secrets.AWS_SERVICE_NAME }}|g" main.tf
          sed -i "s|MODULE_SOURCE_PLACEHOLDER|${{ secrets.TERRAFORM_MODULE_SOURCE }}//module?ref=${{ env.ENVIRONMENT }}|g" main.tf
          sed -i "s|DOMAIN_NAME_PLACEHOLDER|${{ secrets.DOMAIN_NAME }}|g" main.tf
          sed -i "s|ENDPOINT_PLACEHOLDER|${{ env.ENDPOINT }}|g" main.tf

      - name: Terraform Init
        working-directory: "./infrastructure/website"
        run: terraform init

      - name: Terraform Validate
        working-directory: "./infrastructure/website"
        run: terraform validate

      - name: Terraform Plan
        working-directory: "./infrastructure/website"
        run: terraform plan

      - name: Terraform Apply
        working-directory: "./infrastructure/website"
        run: terraform apply -auto-approve

