name: Deploy Website

on:
  # push:
  #   paths:
  #     - "application/**"
  - push

env:
  APPLICATION_DIRECTORY: "./application"

jobs:

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-alexhyett-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-alexhyett-site-build-

      - name: Install dependencies
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm install

      - name: Run unit tests
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm run test:unit

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: cypress-io/github-action@v2
        working-directory: ./application
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3030

  deploy:
    name: Deploy Website
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-alexhyett-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-alexhyett-site-build-

      - name: Install dependencies
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm install

      - name: Run Lint
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm run lint

      - name: Build
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: |
          echo "need to build it"


