name: Validate Infrastructure

on:
  pull_request:
    paths: 
      - "**"
  push:
    paths:
      - "infrastructure/website/**"

env:
  INFRASTRUCTURE_DIRECTORY: "./infrastructure/website"
  SCRIPTS_DIRECTORY: "./scripts"

jobs:
  deploy:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Terraform configuration
        working-directory: ${{ env.SCRIPTS_DIRECTORY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: sh setup-configuration.sh

      - name: Terraform Init
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform validate